/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrderClientRouteImport } from './routes/order-client'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuitesSuiteRoyaleRouteImport } from './routes/suites/suite-royale'
import { Route as SuitesSuiteOliveRouteImport } from './routes/suites/suite-olive'
import { Route as SuitesSuiteJasminRouteImport } from './routes/suites/suite-jasmin'
import { Route as SuitesSuiteAzurRouteImport } from './routes/suites/suite-azur'
import { Route as SuitesSuiteIdRouteImport } from './routes/suites.$suiteId'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as AdminTarifsRouteImport } from './routes/admin.tarifs'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminCheckHouseRouteImport } from './routes/admin.check-house'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAvailabilityRouteImport } from './routes/admin.availability'

const OrderClientRoute = OrderClientRouteImport.update({
  id: '/order-client',
  path: '/order-client',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuitesSuiteRoyaleRoute = SuitesSuiteRoyaleRouteImport.update({
  id: '/suites/suite-royale',
  path: '/suites/suite-royale',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitesSuiteOliveRoute = SuitesSuiteOliveRouteImport.update({
  id: '/suites/suite-olive',
  path: '/suites/suite-olive',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitesSuiteJasminRoute = SuitesSuiteJasminRouteImport.update({
  id: '/suites/suite-jasmin',
  path: '/suites/suite-jasmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitesSuiteAzurRoute = SuitesSuiteAzurRouteImport.update({
  id: '/suites/suite-azur',
  path: '/suites/suite-azur',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitesSuiteIdRoute = SuitesSuiteIdRouteImport.update({
  id: '/suites/$suiteId',
  path: '/suites/$suiteId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTarifsRoute = AdminTarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.clients.lazy').then((d) => d.Route))
const AdminCheckHouseRoute = AdminCheckHouseRouteImport.update({
  id: '/check-house',
  path: '/check-house',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvailabilityRoute = AdminAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/availability': typeof AvailabilityRoute
  '/blog': typeof BlogRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/order-client': typeof OrderClientRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/check-house': typeof AdminCheckHouseRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/tarifs': typeof AdminTarifsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/suites/$suiteId': typeof SuitesSuiteIdRoute
  '/suites/suite-azur': typeof SuitesSuiteAzurRoute
  '/suites/suite-jasmin': typeof SuitesSuiteJasminRoute
  '/suites/suite-olive': typeof SuitesSuiteOliveRoute
  '/suites/suite-royale': typeof SuitesSuiteRoyaleRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/blog': typeof BlogRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/order-client': typeof OrderClientRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/check-house': typeof AdminCheckHouseRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/tarifs': typeof AdminTarifsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/suites/$suiteId': typeof SuitesSuiteIdRoute
  '/suites/suite-azur': typeof SuitesSuiteAzurRoute
  '/suites/suite-jasmin': typeof SuitesSuiteJasminRoute
  '/suites/suite-olive': typeof SuitesSuiteOliveRoute
  '/suites/suite-royale': typeof SuitesSuiteRoyaleRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/availability': typeof AvailabilityRoute
  '/blog': typeof BlogRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/order-client': typeof OrderClientRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/check-house': typeof AdminCheckHouseRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/tarifs': typeof AdminTarifsRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/suites/$suiteId': typeof SuitesSuiteIdRoute
  '/suites/suite-azur': typeof SuitesSuiteAzurRoute
  '/suites/suite-jasmin': typeof SuitesSuiteJasminRoute
  '/suites/suite-olive': typeof SuitesSuiteOliveRoute
  '/suites/suite-royale': typeof SuitesSuiteRoyaleRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/availability'
    | '/blog'
    | '/booking'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/order-client'
    | '/admin/availability'
    | '/admin/blog'
    | '/admin/check-house'
    | '/admin/clients'
    | '/admin/contacts'
    | '/admin/login'
    | '/admin/promotions'
    | '/admin/reservations'
    | '/admin/tarifs'
    | '/blog/$slug'
    | '/suites/$suiteId'
    | '/suites/suite-azur'
    | '/suites/suite-jasmin'
    | '/suites/suite-olive'
    | '/suites/suite-royale'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/availability'
    | '/blog'
    | '/booking'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/order-client'
    | '/admin/availability'
    | '/admin/blog'
    | '/admin/check-house'
    | '/admin/clients'
    | '/admin/contacts'
    | '/admin/login'
    | '/admin/promotions'
    | '/admin/reservations'
    | '/admin/tarifs'
    | '/blog/$slug'
    | '/suites/$suiteId'
    | '/suites/suite-azur'
    | '/suites/suite-jasmin'
    | '/suites/suite-olive'
    | '/suites/suite-royale'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/availability'
    | '/blog'
    | '/booking'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/order-client'
    | '/admin/availability'
    | '/admin/blog'
    | '/admin/check-house'
    | '/admin/clients'
    | '/admin/contacts'
    | '/admin/login'
    | '/admin/promotions'
    | '/admin/reservations'
    | '/admin/tarifs'
    | '/blog_/$slug'
    | '/suites/$suiteId'
    | '/suites/suite-azur'
    | '/suites/suite-jasmin'
    | '/suites/suite-olive'
    | '/suites/suite-royale'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AvailabilityRoute: typeof AvailabilityRoute
  BlogRoute: typeof BlogRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  OrderClientRoute: typeof OrderClientRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SuitesSuiteIdRoute: typeof SuitesSuiteIdRoute
  SuitesSuiteAzurRoute: typeof SuitesSuiteAzurRoute
  SuitesSuiteJasminRoute: typeof SuitesSuiteJasminRoute
  SuitesSuiteOliveRoute: typeof SuitesSuiteOliveRoute
  SuitesSuiteRoyaleRoute: typeof SuitesSuiteRoyaleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/order-client': {
      id: '/order-client'
      path: '/order-client'
      fullPath: '/order-client'
      preLoaderRoute: typeof OrderClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/suites/suite-royale': {
      id: '/suites/suite-royale'
      path: '/suites/suite-royale'
      fullPath: '/suites/suite-royale'
      preLoaderRoute: typeof SuitesSuiteRoyaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suites/suite-olive': {
      id: '/suites/suite-olive'
      path: '/suites/suite-olive'
      fullPath: '/suites/suite-olive'
      preLoaderRoute: typeof SuitesSuiteOliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suites/suite-jasmin': {
      id: '/suites/suite-jasmin'
      path: '/suites/suite-jasmin'
      fullPath: '/suites/suite-jasmin'
      preLoaderRoute: typeof SuitesSuiteJasminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suites/suite-azur': {
      id: '/suites/suite-azur'
      path: '/suites/suite-azur'
      fullPath: '/suites/suite-azur'
      preLoaderRoute: typeof SuitesSuiteAzurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suites/$suiteId': {
      id: '/suites/$suiteId'
      path: '/suites/$suiteId'
      fullPath: '/suites/$suiteId'
      preLoaderRoute: typeof SuitesSuiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tarifs': {
      id: '/admin/tarifs'
      path: '/tarifs'
      fullPath: '/admin/tarifs'
      preLoaderRoute: typeof AdminTarifsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/check-house': {
      id: '/admin/check-house'
      path: '/check-house'
      fullPath: '/admin/check-house'
      preLoaderRoute: typeof AdminCheckHouseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/availability': {
      id: '/admin/availability'
      path: '/availability'
      fullPath: '/admin/availability'
      preLoaderRoute: typeof AdminAvailabilityRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAvailabilityRoute: typeof AdminAvailabilityRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCheckHouseRoute: typeof AdminCheckHouseRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminTarifsRoute: typeof AdminTarifsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAvailabilityRoute: AdminAvailabilityRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCheckHouseRoute: AdminCheckHouseRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminTarifsRoute: AdminTarifsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AvailabilityRoute: AvailabilityRoute,
  BlogRoute: BlogRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  OrderClientRoute: OrderClientRoute,
  BlogSlugRoute: BlogSlugRoute,
  SuitesSuiteIdRoute: SuitesSuiteIdRoute,
  SuitesSuiteAzurRoute: SuitesSuiteAzurRoute,
  SuitesSuiteJasminRoute: SuitesSuiteJasminRoute,
  SuitesSuiteOliveRoute: SuitesSuiteOliveRoute,
  SuitesSuiteRoyaleRoute: SuitesSuiteRoyaleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
